import * as vscode from 'vscode';

export class LuaCompletionProvider implements vscode.CompletionItemProvider {
    provideCompletionItems(
        document: vscode.TextDocument,
        position: vscode.Position
    ): vscode.CompletionItem[] {
        const items: vscode.CompletionItem[] = [];

        const functions = [
            "SpawnArrow",
            "SpawnGrenade",
            "SpawnAbilityPickup",
            "SpawnSmokeGrenade",
            "SpawnExplosion",
            "SpawnBoulder",
            "SpawnPlatform",
            "RaycastRoundedRect",
            "GetClosestPlayer",
            "GetAllPlatforms",
            "GetAllPlayers",
            "GetAllBoplBodys",
            "ShootBlink",
            "ShootGrow",
            "ShootShrink",
            "GetDeltaTime",
            "GetTimeSinceLevelLoad",
            "IsTimeStopped",
            "GetInputValueWithId",
            "SetOutputWithId",
            "GetFileFromMapFile",
            "GetSpeed",
            "GetGroundedSpeed",
            "GetMaxSpeed",
            "GetJumpStrength",
            "GetAccel",
            "GetGravityAccel",
            "GetGravityMaxFallSpeed",
            "GetJumpExtraXStrength",
            "GetJumpKeptMomentum",
            "GetAirAccel",
            "GetMass",
            "GetPosition",
            "SetPosition",
            "SetSpeed",
            "SetGroundedSpeed",
            "SetMaxSpeed",
            "SetJumpStrength",
            "SetAccel",
            "SetGravityAccel",
            "SetGravityMaxFallSpeed",
            "SetJumpExtraXStrength",
            "SetJumpKeptMomentum",
            "SetAirAccel",
            "SetMass",
            "AddForce",
            "GetAbility",
            "SetAbility",
            "GetAbilityCount",
            "GetAbilityCooldownRemaining",
            "SetAbilityCooldownRemaining",
            "GetAbilityMaxCooldown",
            "IsDisappeared",
            "GetPlatform",
            "GetClassType",
            "GetHome",
            "GetHomeRot",
            "GetScale",
            "SetScale",
            "SetHome",
            "SetHomeRot",
            "ShakePlatform",
            "DropAllPlayers",
            "GetBaseScale",
            "SetBaseScale",
            "GetPlatformType",
            "GetBoplBody",
            "IsBoulder",
            "IsResizable",
            "ResizePlatform",
            "GetPlatformSize",
            "GetTrueWidthAndHeight",
            "GetClassType",
            "HasBeenInitialized",
            "IsBeingDestroyed",
            "GetPos",
            "GetRot",
            "GetScale",
            "GetMass",
            "GetVelocity",
            "SetPos",
            "SetRot",
            "SetScale",
            "SetVelocity",
            "SetMass",
            "AddForce",
            "Destroy",
            "IsDisappeared",
            "SetColor",
            "GetObjectType",
            "GetInputValueWithId",
            "SetOutputWithId",
            "GetFileFromMapFile"
        ];

        functions.forEach(func => {
            items.push(new vscode.CompletionItem(func, vscode.CompletionItemKind.Function));
        });

        return items;
    }
}
